cargo-features = ["metabuild"]

[package]
name = "try_metabuild"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
edition = "2018"
metabuild = ["clib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies.clib]
path = "/home/abscon/crates/clib"

[package.metadata.clib]
build-pkgs = ["tk86"]

[package.metadata.clib.pkgs]
x11 = { headers = ["X11/Xlib.h"] }
tcl86 = { headers = ["tcl.h"] }
tk86 = { headers = ["tk.h"], dependencies = ["tcl86"], header-dependencies = ["x11"] }
